# Generated by Django 5.0 on 2024-04-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
